import { Product, Sale, Employee, SaleProduct } from '../types';

export const getSampleProducts = (): Product[] => [
  {
    id: '1',
    name: 'Gel Polish Rose Quartz',
    description: 'Tono nude rosado de larga duración con acabado brillante.',
    price: 12.99,
    cost: 5.2,
    category: 'Gel Polish',
    sku: 'GEL-ROSE-01',
    stock: 120,
    minStock: 30,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'UV LED Lamp Pro 54W',
    description: 'Lámpara profesional con sensor automático y doble temporizador.',
    price: 89.99,
    cost: 46.0,
    category: 'Equipment',
    sku: 'LAMP-UV-54',
    stock: 18,
    minStock: 5,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Acrylic Powder Crystal Clear 1kg',
    description: 'Polvo acrílico cristal para aplicaciones resistentes y sin burbujas.',
    price: 39.5,
    cost: 18.0,
    category: 'Acrylic System',
    sku: 'ACR-CLR-1K',
    stock: 24,
    minStock: 10,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Cuticle Oil Pen Trio',
    description: 'Aceite hidratante con aroma a rosas en práctico formato de pluma.',
    price: 14.99,
    cost: 6.2,
    category: 'Care',
    sku: 'CARE-OIL-03',
    stock: 200,
    minStock: 40,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Nail Art Brush Set Deluxe',
    description: 'Set de 7 brochas profesionales para nail art detallado.',
    price: 24.99,
    cost: 11.5,
    category: 'Accessories',
    sku: 'BRU-DEL-07',
    stock: 48,
    minStock: 12,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const getSampleEmployees = (): Employee[] => [
  {
    id: '1',
    userId: '2', // Links to user with ID 2
    employeeId: 'EMP001',
    firstName: 'Camila',
    lastName: 'Reyes',
    email: 'camila@todoparunas.com',
    phone: '+52-55-0001-0001',
    department: 'Sales',
    position: 'Store Manager',
    hireDate: new Date('2022-08-10').toISOString(),
    salary: 42000,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    userId: '3', // Links to user with ID 3
    employeeId: 'EMP002',
    firstName: 'Valeria',
    lastName: 'Lopez',
    email: 'valeria@todoparunas.com',
    phone: '+52-55-0001-0002',
    department: 'Operations',
    position: 'Inventory Specialist',
    hireDate: new Date('2023-02-18').toISOString(),
    salary: 36000,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const getSampleSales = (): Sale[] => [
  {
    id: '1',
    customerId: '1',
    customerName: 'Diana Morales',
    employeeId: '1',
    employeeName: 'Camila Reyes',
    products: [
      {
        productId: '1',
        productName: 'Gel Polish Rose Quartz',
        quantity: 20,
        unitPrice: 12.99,
        totalPrice: 259.8,
      },
      {
        productId: '4',
        productName: 'Cuticle Oil Pen Trio',
        quantity: 10,
        unitPrice: 14.99,
        totalPrice: 149.9,
      },
    ],
    totalAmount: 409.7,
    discount: 20.0,
    finalAmount: 389.7,
    status: 'completed',
    paymentMethod: 'transfer',
    saleDate: new Date().toISOString(),
    notes: 'Entrega programada para lunes antes de apertura.',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    customerId: '2',
    customerName: 'Paola Rivera',
    employeeId: '1',
    employeeName: 'Camila Reyes',
    products: [
      {
        productId: '2',
        productName: 'UV LED Lamp Pro 54W',
        quantity: 3,
        unitPrice: 89.99,
        totalPrice: 269.97,
      },
      {
        productId: '5',
        productName: 'Nail Art Brush Set Deluxe',
        quantity: 6,
        unitPrice: 24.99,
        totalPrice: 149.94,
      },
    ],
    totalAmount: 419.91,
    discount: 0,
    finalAmount: 419.91,
    status: 'completed',
    paymentMethod: 'card',
    saleDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    customerId: '3',
    customerName: 'Laura Torres',
    employeeId: '2',
    employeeName: 'Valeria Lopez',
    products: [
      {
        productId: '3',
        productName: 'Acrylic Powder Crystal Clear 1kg',
        quantity: 5,
        unitPrice: 39.5,
        totalPrice: 197.5,
      },
      {
        productId: '1',
        productName: 'Gel Polish Rose Quartz',
        quantity: 12,
        unitPrice: 12.99,
        totalPrice: 155.88,
      },
    ],
    totalAmount: 353.38,
    discount: 25.0,
    finalAmount: 328.38,
    status: 'pending',
    paymentMethod: 'transfer',
    saleDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Pendiente confirmación de depósito para liberar envío.',
    createdAt: new Date().toISOString(),
  },
];
