import { Product, Sale, Employee, SaleProduct } from '../types';

export const getSampleProducts = (): Product[] => [
  {
    id: '1',
    name: 'Laptop Pro 15"',
    description: 'High-performance laptop for professionals',
    price: 1299.99,
    cost: 800.00,
    category: 'Electronics',
    sku: 'LAP-PRO-15',
    stock: 25,
    minStock: 5,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse with precision tracking',
    price: 49.99,
    cost: 20.00,
    category: 'Accessories',
    sku: 'MOU-WIR-001',
    stock: 150,
    minStock: 20,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Mechanical Keyboard',
    description: 'RGB mechanical keyboard with blue switches',
    price: 89.99,
    cost: 45.00,
    category: 'Accessories',
    sku: 'KEY-MEC-001',
    stock: 8,
    minStock: 10,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Monitor 27" 4K',
    description: 'Ultra HD 4K monitor with HDR support',
    price: 399.99,
    cost: 250.00,
    category: 'Electronics',
    sku: 'MON-4K-27',
    stock: 12,
    minStock: 5,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Office Chair',
    description: 'Ergonomic office chair with lumbar support',
    price: 199.99,
    cost: 120.00,
    category: 'Furniture',
    sku: 'CHA-OFF-001',
    stock: 3,
    minStock: 5,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const getSampleEmployees = (): Employee[] => [
  {
    id: '1',
    userId: '2', // Links to user with ID 2
    employeeId: 'EMP001',
    firstName: 'John',
    lastName: 'Doe',
    email: 'employee1@crm.com',
    phone: '+1-555-0002',
    department: 'Sales',
    position: 'Sales Representative',
    hireDate: new Date('2023-01-15').toISOString(),
    salary: 45000,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    userId: '3', // Links to user with ID 3
    employeeId: 'EMP002',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'employee2@crm.com',
    phone: '+1-555-0003',
    department: 'Marketing',
    position: 'Marketing Specialist',
    hireDate: new Date('2023-03-20').toISOString(),
    salary: 42000,
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const getSampleSales = (): Sale[] => [
  {
    id: '1',
    customerId: '1',
    customerName: 'John Smith',
    employeeId: '1',
    employeeName: 'John Doe',
    products: [
      {
        productId: '1',
        productName: 'Laptop Pro 15"',
        quantity: 1,
        unitPrice: 1299.99,
        totalPrice: 1299.99,
      },
      {
        productId: '2',
        productName: 'Wireless Mouse',
        quantity: 1,
        unitPrice: 49.99,
        totalPrice: 49.99,
      },
    ],
    totalAmount: 1349.98,
    discount: 50.00,
    finalAmount: 1299.98,
    status: 'completed',
    paymentMethod: 'card',
    saleDate: new Date().toISOString(),
    notes: 'Customer preferred card payment',
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    customerId: '2',
    customerName: 'Sarah Johnson',
    employeeId: '1',
    employeeName: 'John Doe',
    products: [
      {
        productId: '3',
        productName: 'Mechanical Keyboard',
        quantity: 2,
        unitPrice: 89.99,
        totalPrice: 179.98,
      },
    ],
    totalAmount: 179.98,
    discount: 0,
    finalAmount: 179.98,
    status: 'completed',
    paymentMethod: 'cash',
    saleDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    customerId: '3',
    customerName: 'Mike Davis',
    employeeId: '2',
    employeeName: 'Jane Smith',
    products: [
      {
        productId: '4',
        productName: 'Monitor 27" 4K',
        quantity: 1,
        unitPrice: 399.99,
        totalPrice: 399.99,
      },
      {
        productId: '5',
        productName: 'Office Chair',
        quantity: 1,
        unitPrice: 199.99,
        totalPrice: 199.99,
      },
    ],
    totalAmount: 599.98,
    discount: 100.00,
    finalAmount: 499.98,
    status: 'pending',
    paymentMethod: 'transfer',
    saleDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    notes: 'Pending bank transfer',
    createdAt: new Date().toISOString(),
  },
];
