import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const dashboardStyles = StyleSheet.create({
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 18,
    justifyContent: 'space-between',
  },
  statCard: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 24,
    width: (width - 52) / 2,
    marginBottom: 14,
    elevation: 8,
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#e0e7ff',
    borderTopWidth: 6,
    borderTopColor: '#6366f1',
  },
  statNumber: {
    fontSize: 30,
    fontWeight: '900',
    color: '#6366f1',
    marginBottom: 8,
    letterSpacing: -0.5,
    textShadowColor: 'rgba(99, 102, 241, 0.1)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  statLabel: {
    fontSize: 12,
    color: '#64748b',
    textAlign: 'center',
    fontWeight: '700',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  recentSection: {
    backgroundColor: 'white',
    margin: 18,
    borderRadius: 20,
    padding: 24,
    elevation: 6,
    shadowColor: '#6366f1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    borderLeftWidth: 5,
    borderLeftColor: '#6366f1',
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1e293b',
    letterSpacing: 0.3,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  activityIcon: {
    fontSize: 18,
    marginRight: 12,
  },
  activityContent: {
    flex: 1,
  },
  activityTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1e293b',
    marginBottom: 3,
    letterSpacing: 0.1,
  },
  activitySubtitle: {
    fontSize: 12,
    color: '#64748b',
    fontWeight: '500',
  },
  activityDate: {
    fontSize: 11,
    color: '#94a3b8',
    fontWeight: '500',
  },
  alertSection: {
    backgroundColor: '#fef2f2',
    margin: 18,
    borderRadius: 20,
    padding: 20,
    elevation: 6,
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    borderLeftWidth: 5,
    borderLeftColor: '#ef4444',
  },
  alertTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#dc2626',
    letterSpacing: 0.3,
  },
  alertItem: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#fecaca',
    marginBottom: 4,
  },
  alertText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#991b1b',
    marginBottom: 4,
  },
  alertDate: {
    fontSize: 13,
    color: '#991b1b',
    fontWeight: '600',
  },
  noteItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  noteItemTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1e293b',
    marginBottom: 4,
  },
  noteItemContent: {
    fontSize: 12,
    color: '#64748b',
    marginBottom: 4,
  },
  noteItemDate: {
    fontSize: 11,
    color: '#94a3b8',
  },
});
